blank_issues_enabled: true
contact_links:
  - name: Question or usage help
    url: https://github.com/deepakvijayakumar14/kotlin-snowflake/discussions
    about: For "how do I…" questions, rather than defects.
